import { Component, OnInit } from '@angular/core';
import { AdminService } from '../../core/services/admin.service';
import { Report } from '../../core/models/models';

@Component({
  selector: 'app-reports',
  template: `
    <div class="page-container animate-fade-in">
      <div class="page-header">
        <div>
          <h1>Reports & Analytics</h1>
          <p>Generate and view operational reports</p>
        </div>
      </div>

      <!-- Generate Report -->
      <div class="card" style="margin-bottom:32px">
        <h3 style="margin-bottom:20px">📊 Generate Report</h3>
        <div style="display:flex;gap:12px;flex-wrap:wrap">
          <button class="btn btn-primary" (click)="generate('DELIVERY_SUMMARY','Delivery Summary Report')">
            <span class="material-icons">summarize</span> Delivery Summary
          </button>
          <button class="btn btn-secondary" (click)="generate('PERFORMANCE','Performance Report')">
            <span class="material-icons">trending_up</span> Performance
          </button>
          <button class="btn btn-secondary" (click)="generate('HUB_UTILIZATION','Hub Utilization Report')">
            <span class="material-icons">hub</span> Hub Utilization
          </button>
        </div>
        <div *ngIf="genMsg" style="margin-top:16px;color:var(--success);font-size:13px">{{ genMsg }}</div>
      </div>

      <!-- Reports List -->
      <div class="card">
        <h3 style="margin-bottom:20px">📋 Generated Reports</h3>
        <div *ngIf="loading" class="loader"><div class="spinner"></div></div>
        <div *ngIf="!loading && reports.length === 0" style="text-align:center;padding:40px;color:var(--text-muted)">
          No reports generated yet. Click a button above to create one.
        </div>
        <div class="table-container" *ngIf="!loading && reports.length > 0">
          <table>
            <thead>
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Type</th>
                <th>Generated By</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let r of reports">
                <td>{{ r.id }}</td>
                <td><strong>{{ r.title }}</strong></td>
                <td><span class="badge badge-booked">{{ r.type }}</span></td>
                <td>{{ r.generatedBy }}</td>
                <td>{{ r.generatedAt | date:'medium' }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  `
})
export class ReportsComponent implements OnInit {
  reports: Report[] = [];
  loading = true;
  genMsg = '';

  constructor(private adminService: AdminService) {}

  ngOnInit() {
    this.loadReports();
  }

  loadReports() {
    this.adminService.getReports().subscribe({
      next: (data) => { this.reports = data; this.loading = false; },
      error: () => { this.loading = false; }
    });
  }

  generate(type: string, title: string) {
    this.adminService.generateReport(type, title).subscribe({
      next: () => {
        this.genMsg = `${title} generated successfully!`;
        this.loadReports();
        setTimeout(() => this.genMsg = '', 3000);
      }
    });
  }
}
