import { Component, inject, OnInit } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ToastService } from '../../../services/toast';
import { LoadingSpinnerComponent } from '../../../components/shared/loading-spinner/loading-spinner';
import { AdminService } from '../../../services/admin';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, LoadingSpinnerComponent, DatePipe],
  templateUrl: './reports.html',
  styleUrls: ['./reports.css']
})
export class ReportsPage implements OnInit {
  private fb = inject(FormBuilder);
  private toast = inject(ToastService);
  private adminService = inject(AdminService);

  pastReports: any[] = [];
  showReportModal = false;
  isGenerating = false;
  generatedReport: any = null;

  reportForm: FormGroup = this.fb.group({
    title: ['', Validators.required],
    type: ['DELIVERY_SUMMARY', Validators.required]
  });

  ngOnInit() {
    this.loadReports();
  }

  loadReports() {
    this.adminService.getReports().subscribe({
      next: (data) => this.pastReports = data || [],
      error: () => this.toast.showError('Failed to load reports')
    });
  }

  generateReport() {
    if (this.reportForm.valid) { 
      this.isGenerating = true;
      this.adminService.generateReport(this.reportForm.value).subscribe({
        next: (res) => {
          this.isGenerating = false;
          // Parse the data string into display-friendly key/value pairs
          let dataItems: { label: string; value: string }[] = [];
          try {
            const raw = res.data || '{}';
            const cleaned = raw.replace(/^\{/, '').replace(/\}$/, '');
            dataItems = cleaned.split(',').map((entry: string) => {
              const [k, ...rest] = entry.split('=');
              return { label: k?.trim(), value: rest.join('=').trim() };
            }).filter((i: any) => i.label);
          } catch (_) {}
          this.generatedReport = { ...res, dataItems };
          this.toast.showSuccess('Report generated successfully');
          this.showReportModal = false;
          this.loadReports();
        },
        error: (err) => {
          this.toast.showError('Report generation failed');
          this.isGenerating = false;
        }
      });
    }
  }

  downloadReport(report?: any) {
    const target = report || this.generatedReport;
    if (!target) return;

    // Build CSV from dataItems or raw data
    const rows: string[][] = [['Field', 'Value']];
    if (target.dataItems && target.dataItems.length > 0) {
      target.dataItems.forEach((item: any) => rows.push([item.label, item.value]));
    } else {
      rows.push(['Title', target.title || '']);
      rows.push(['Type', target.type || '']);
      rows.push(['Generated At', target.generatedAt || '']);
      rows.push(['Generated By', target.generatedBy || '']);
    }

    const csv = rows.map(r => r.map(v => `"${String(v).replace(/"/g, '""')}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(target.title || 'report').replace(/\s+/g, '_')}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    this.toast.showSuccess('Report downloaded as CSV');
  }
}
